Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv..csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
8760,6339,-2.262193,2.436048,-1.230114,-1.257178,1.999487,3.164989,-0.326910,1.328598,2.010502,...,-0.731751,-1.249195,0.056359,0.847677,0.249961,-0.028339,-0.172882,-0.635326,1.98,0.0
8761,6340,-1.134217,0.166310,1.306848,1.667260,-0.570757,0.814229,2.103197,-0.383550,0.271516,...,-0.153814,-0.043290,0.669085,-0.108929,-0.698489,-0.466839,0.030775,-0.161917,379.63,0.0
8762,6345,-0.865862,0.295617,3.940337,3.606141,-0.672490,1.242731,-0.897963,0.364253,1.896719,...,-0.090057,0.610083,-0.276843,0.387543,0.185369,0.486753,0.210990,-0.056815,21.48,0.0
8763,6345,1.203971,0.927268,0.041463,1.669881,-0.007861,-1.477041,0.300909,-0.418894,1.000914,...,-0.171369,-0.125577,-0.058487,0.751805,0.632035,-0.402436,0.015976,0.058703,1.00,0.0
8764,6347,1.122792,-0.064138,1.035259,1.775286,-0.649522,0.282818,-0.613878,0.206216,2.458567,...,-0.259434,-0.220765,-0.033708,-0.005861,0.523800,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8765 entries, 0 to 8764
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    8765 non-null   int64
 1   V1      8765 non-null   float64
 2   V2      8765 non-null   float64
 3   V3      8765 non-null   float64
 4   V4      8765 non-null   float64
 5   V5      8765 non-null   float64
 6   V6      8765 non-null   float64
 7   V7      8765 non-null   float64
 8   V8      8765 non-null   float64
 9   V9      8765 non-null   float64
 10  V10     8765 non-null   float64
 11  V11     8764 non-null   float64
 12  V12     8764 non-null   float64
 13  V13     8764 non-null   float64
 14  V14     8764 non-null   float64
 15  V15     8764 non-null   float64
 16  V16     8764 non-null   float64
 17  V17     8764 non-null   float64
 18  V18     8764 non-null   float64
 19  V19     8764 non-null   float64
 20  V20     8764 non-null   float64
 21  V21     8764 non-null   float64
 22  V22     8764 non-null   float64
 23  V23     8764 non-null   float64
 24  V24     8764 non-null   float64
 25  V25     8764 non-null   float64
 26  V26     8763 non-null   float64
 27  V27     8763 non-null   float64
 28  V28     8763 non-null   float64
 29  Amount  8763 non-null   float64
 30  Class   8762 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 2.1 MB

In [ ]:
# checking the number of missingvalues in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       2
V27       2
V28       2
Amount    2
Class     3
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    8740
1.0      22
Name: Class, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(8740, 31)
(22, 31)

In [ ]:
# satistical measures of the data
legit.Amount.describe()

count    8740.000000
mean       63.030016
std       178.177481
min         0.000000
25%         5.000000
50%        15.000000
75%        52.175000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      22.000000
mean      144.768636
std       310.019575
min         0.000000
25%         1.000000
50%         2.395000
75%       142.342500
max      1218.890000
Name: Amount, dtype: float64

In [ ]:
# compare the value for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,7109.101030,-0.190746,0.266470,0.879429,0.198349,-0.065781,0.188527,-0.071746,-0.027589,0.727428,...,0.033344,-0.053508,-0.157315,-0.031147,0.018529,0.107720,-0.008130,0.015212,0.002758,63.030016
1.0,13891.727273,-5.583648,4.472396,-8.905382,6.955225,-3.365357,-1.667367,-7.659948,1.117496,-3.023520,...,0.380155,0.375114,0.108297,-0.727336,-0.433636,-0.455846,0.195049,0.543628,-0.097227,144.768636

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
 new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1608,1251,-4.479014,-2.884368,0.633375,0.224652,-1.047208,1.392407,2.620458,-1.099184,1.710955,...,-1.272095,0.403637,1.509692,-0.547387,0.577319,1.175117,0.235720,0.695821,500.00,0.0
6337,2929,0.634486,1.577963,-1.473381,1.608998,1.299569,-1.578738,1.271221,-0.603646,0.086616,...,-0.235057,0.062311,0.156436,0.053852,-0.553130,-0.441358,0.065313,-0.379360,1.59,0.0
2935,11957,-0.665406,1.503375,1.616487,0.946400,0.807342,-0.813798,1.333585,-0.699875,0.275743,...,-0.092869,0.140483,-0.446905,0.379424,0.652086,-0.259554,-0.410643,-0.146255,0.89,0.0
1194,926,-1.536958,-0.041422,0.629846,-0.687015,0.796080,-0.485757,-0.302744,0.737427,-0.069131,...,-0.107957,-0.701171,-0.184521,-0.851564,-0.129501,0.345511,0.178534,-0.054153,1.00,0.0
633,481,-2.752124,-3.232168,0.873036,0.108217,-2.451279,0.486159,3.152907,-1.013087,1.128326,...,-0.299791,-0.003767,0.545794,0.853981,-0.943651,0.607826,0.335131,-0.561721,1015.61,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
4958,18399,-14.474437,6.503185,-17.712632,11.270352,-4.150142,-3.372098,-16.535807,-1.443947,-6.815273,...,-2.475962,0.342391,-3.564508,-0.818140,0.153408,0.755079,2.706566,-0.992916,1.00,1.0
5048,18675,-12.339603,4.488267,-16.587073,10.107274,-10.420199,0.130670,-15.600323,-1.157696,-5.304631,...,-2.089610,1.745315,1.376816,-0.554271,-1.610741,0.153725,1.212477,-1.869290,188.78,1.0
5054,18690,-15.398845,7.472324,-19.026912,11.165526,-6.893856,-2.120937,-14.913330,-0.721214,-7.175097,...,-2.444884,0.727495,-0.345078,-0.981749,0.995271,0.816762,2.262942,-1.178063,1.00,1.0
5500,19762,-14.179165,7.421370,-21.405836,11.927512,-7.974281,-2.202710,-15.471612,-0.356595,-6.380125,...,-2.366836,1.130955,0.991153,-1.033132,-0.327179,0.634693,2.171905,-1.395288,1.00,1.0
7837,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    492
1.0     22
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,7465.327236,-0.218268,0.314756,0.898432,0.214648,-0.054066,0.213252,-0.019376,0.012938,0.74128,...,-0.008552,-0.002501,-0.129699,-0.048522,-0.011480,0.097830,-0.020058,0.008066,-0.003496,64.119085
1.0,13891.727273,-5.583648,4.472396,-8.905382,6.955225,-3.365357,-1.667367,-7.659948,1.117496,-3.02352,...,0.380155,0.375114,0.108297,-0.727336,-0.433636,-0.455846,0.195049,0.543628,-0.097227,144.768636

Spliting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

       Time         V1        V2         V3         V4         V5        V6  \
1608   1251  -4.479014 -2.884368   0.633375   0.224652  -1.047208  1.392407
6337   2929   0.634486  1.577963  -1.473381   1.608998   1.299569 -1.578738
2935  11957  -0.665406  1.503375   1.616487   0.946400   0.807342 -0.813798
1194    926  -1.536958 -0.041422   0.629846  -0.687015   0.796080 -0.485757
633     481  -2.752124 -3.232168   0.873036   0.108217  -2.451279  0.486159
...     ...        ...       ...        ...        ...        ...       ...
4958  18399 -14.474437  6.503185 -17.712632  11.270352  -4.150142 -3.372098
5048  18675 -12.339603  4.488267 -16.587073  10.107274 -10.420199  0.130670
5054  18690 -15.398845  7.472324 -19.026912  11.165526  -6.893856 -2.120937
5500  19762 -14.179165  7.421370 -21.405836  11.927512  -7.974281 -2.202710
7837   4462  -2.303350  1.759247  -0.359745   2.330243  -0.821628 -0.075788

             V7        V8        V9  ...       V20       V21       V22  \
1608   2.620458 -1.099184  1.710955  ... -1.532972 -1.272095  0.403637
6337   1.271221 -0.603646  0.086616  ...  0.325103 -0.235057  0.062311
2935   1.333585 -0.699875  0.275743  ...  0.107885 -0.092869  0.140483
1194  -0.302744  0.737427 -0.069131  ...  0.134666 -0.107957 -0.701171
633    3.152907 -1.013087  1.128326  ... -0.102130 -0.299791 -0.003767
...         ...       ...       ...  ...       ...       ...       ...
4958 -16.535807 -1.443947 -6.815273  ...  1.101250 -2.475962  0.342391
5048 -15.600323 -1.157696 -5.304631  ... -0.085501 -2.089610  1.745315
5054 -14.913330 -0.721214 -7.175097  ...  1.111502 -2.444884  0.727495
5500 -15.471612 -0.356595 -6.380125  ...  1.002764 -2.366836  1.130955
7837   0.562320 -0.399147 -0.238253  ... -0.430022 -0.294166 -0.932391

           V23       V24       V25       V26       V27       V28   Amount
1608  1.509692 -0.547387  0.577319  1.175117  0.235720  0.695821   500.00
6337  0.156436  0.053852 -0.553130 -0.441358  0.065313 -0.379360     1.59
2935 -0.446905  0.379424  0.652086 -0.259554 -0.410643 -0.146255     0.89
1194 -0.184521 -0.851564 -0.129501  0.345511  0.178534 -0.054153     1.00
633   0.545794  0.853981 -0.943651  0.607826  0.335131 -0.561721  1015.61
...        ...       ...       ...       ...       ...       ...      ...
4958 -3.564508 -0.818140  0.153408  0.755079  2.706566 -0.992916     1.00
5048  1.376816 -0.554271 -1.610741  0.153725  1.212477 -1.869290   188.78
5054 -0.345078 -0.981749  0.995271  0.816762  2.262942 -1.178063     1.00
5500  0.991153 -1.033132 -0.327179  0.634693  2.171905 -1.395288     1.00
7837  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029   239.93

[514 rows x 30 columns]

In [ ]:
print(Y)

1608    0.0
6337    0.0
2935    0.0
1194    0.0
633     0.0
       ...
4958    1.0
5048    1.0
5054    1.0
5500    1.0
7837    1.0
Name: Class, Length: 514, dtype: float64

Split the data into Training data & Testing data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(514, 30) (411, 30) (103, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on training data: ', training_data_accuracy)

Accuracy on training data:  0.9854014598540146

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data: ', test_data_accuracy)

Accuracy score on Test Data:  0.9902912621359223